services:
  redisearch:
    image: redislabs/redisearch:2.6.6
    ports:
      - 6379:6379
    volumes:
      - ./data:/data
    command: redis-server --loadmodule /usr/lib/redis/modules/redisearch.so